### ISSUE TITLE
Handle weird dates

### ISSUE THREAD

**Issue by saibaggins** [HeartfulnessInstitute/event-summary-bot#5]

**Comment by icyphox** [comment]
I believe I wrote the existing code that handles the dates. Can you elaborate further on the bug?  
Edit: Oh it appears to be fixed in https://github.com/HeartfulnessInstitute/event-summary-bot/commit/1f105fcd5d5c5fa992369190031b24117362c57b (?)

**Comment by saibaggins** [comment]
I put a workaround to force the final date to be today if it's entered in the future ("tomorrow", or >12 for months, >31 for days etc.). But would be nice to actually validate and reject the date entry if invalid until a valid date is entered.

**Comment by saibaggins** [comment]
Done for now.
